set -g default-terminal 'tmux-256color'
set -as terminal-features ',alacritty*:RGB:clipboard'
set -s set-clipboard external
setw -g xterm-keys on
set -s escape-time 10                     # faster command sequences
set -sg repeat-time 600                   # increase repeat timeout
set -s focus-events on

set -g mouse off

unbind C-b
set -g prefix C-a
bind C-a last-window
bind a send-prefix

set -g history-limit 100000                 # boost history

bind r source-file ~/.tmux.conf \; display '~/.tmux.conf sourced'

setw -g automatic-rename on   # rename window to reflect current program
set -g renumber-windows on    # renumber windows when a window is closed
set -g set-titles on          # set terminal title
set -g set-titles-string "#{user}@#H in #{pane_current_path}: #{pane_current_command}"

# activity
set -g monitor-activity on
set -g visual-activity off

# pane navigation
bind -r h select-pane -L  # move left
bind -r j select-pane -D  # move down
bind -r k select-pane -U  # move up
bind -r l select-pane -R  # move right

set -g status-keys vi
setw -g mode-keys vi

# copy through OSC 52
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# Highlight active window
setw -g window-status-current-style "bg=red,fg=white"
